disk-io.opic: disk-io.c \
 ../../../tools/config.h \
 kerncompat.h radix-tree.h ctree.h list.h extent-cache.h rbtree.h \
 extent_io.h ioctl.h disk-io.h volumes.h transaction.h crc32c.h utils.h \
 internal.h btrfs-list.h print-tree.h rbtree-utils.h
