free-space-cache.opic: free-space-cache.c \
 ../../../tools/config.h \
 kerncompat.h ctree.h list.h radix-tree.h extent-cache.h rbtree.h \
 extent_io.h ioctl.h free-space-cache.h transaction.h disk-io.h crc32c.h \
 bitops.h internal.h
