fsys_btrfs.opic: fsys_btrfs.c \
 ../../../tools/config.h \
 ../../../tools/libfsimage/common/xenfsimage_plugin.h \
 ../../../tools/libfsimage/common/xenfsimage.h \
 kerncompat.h ctree.h list.h radix-tree.h extent-cache.h rbtree.h \
 extent_io.h ioctl.h disk-io.h internal.h volumes.h
