/*
 * Automatically generated by /home/builder/rpmbuild/BUILD/xen-4.13.5/xen/../xen/tools/gen-cpuid.py - Do not edit!
 * Source data: /home/builder/rpmbuild/BUILD/xen-4.13.5/xen/../xen/include/public/arch-x86/cpufeatureset.h
 */
#ifndef __XEN_X86__FEATURESET_DATA__
#define __XEN_X86__FEATURESET_DATA__

#define FEATURESET_NR_ENTRIES 22

#define CPUID_COMMON_1D_FEATURES 0x0183f3ffU

#define INIT_KNOWN_FEATURES { \
    0xbfebfbffU, \
    0xfffef3ffU, \
    0xee500800U, \
    0x2469bfffU, \
    0x0000000fU, \
    0xfdbfffffU, \
    0x02405fdfU, \
    0x00000500U, \
    0x770fd205U, \
    0xbc102e0cU, \
    0x00000020U, \
    0x38000004U, \
    0x00000000U, \
    0x0000003fU, \
    0x00000000U, \
    0x00000000U, \
    0x07beffffU, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
}

#define INIT_SPECIAL_FEATURES { \
    0x10000200U, \
    0x88200000U, \
    0x00000000U, \
    0x00000002U, \
    0x00000000U, \
    0x01002850U, \
    0x00000010U, \
    0x00000000U, \
    0x00000000U, \
    0x20000800U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00080004U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
}

#define INIT_PV_FEATURES { \
    0x1fc9cbf5U, \
    0xf6f83203U, \
    0xea500800U, \
    0x042109e3U, \
    0x00000007U, \
    0xfdaf0b29U, \
    0x02405f43U, \
    0x00000000U, \
    0x64001005U, \
    0xac00040cU, \
    0x00000020U, \
    0x38000004U, \
    0x00000000U, \
    0x00000021U, \
    0x00000000U, \
    0x00000000U, \
    0x0512e173U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
}

#define INIT_HVM_SHADOW_FEATURES { \
    0x1fcbfbffU, \
    0xf7f83223U, \
    0xea500800U, \
    0x042109f7U, \
    0x0000000fU, \
    0xfdbf0babU, \
    0x02405f47U, \
    0x00000000U, \
    0x750fd005U, \
    0xbc00040cU, \
    0x00000020U, \
    0x38000004U, \
    0x00000000U, \
    0x00000021U, \
    0x00000000U, \
    0x00000000U, \
    0x0512e173U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
}

#define INIT_HVM_HAP_FEATURES { \
    0x1fcbfbffU, \
    0xf7fa3223U, \
    0xee500800U, \
    0x042109f7U, \
    0x0000000fU, \
    0xfdbf0fabU, \
    0x02405f4fU, \
    0x00000000U, \
    0x750fd005U, \
    0xbc00040cU, \
    0x00000020U, \
    0x38000004U, \
    0x00000000U, \
    0x00000021U, \
    0x00000000U, \
    0x00000000U, \
    0x0512e173U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
}

#define NR_DEEP_DEPS 28U

#define INIT_DEEP_FEATURES { \
    0x07800259U, \
    0x16080203U, \
    0xa0100000U, \
    0x00000000U, \
    0x00000000U, \
    0x40010020U, \
    0x00000000U, \
    0x00000000U, \
    0x0000d000U, \
    0x24000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000002U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
    0x00000000U, \
}

#define INIT_DEEP_DEPS { \
    { 0x0U, /* FPU */ { \
        0x00800000U, \
        0x00000000U, \
        0xc0400000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x3U, /* PSE */ { \
        0x00020000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x4U, /* TSC */ { \
        0x00000000U, \
        0x01000000U, \
        0x08000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000002U, \
        0x00000000U, \
        0x00000100U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x6U, /* PAE */ { \
        0x00000000U, \
        0x00022000U, \
        0x24100000U, \
        0x00000001U, \
        0x00000000U, \
        0x00100000U, \
        0x00000008U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x9U, /* APIC */ { \
        0x00000000U, \
        0x01200000U, \
        0x00000000U, \
        0x00000008U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x17U, /* MMX */ { \
        0x00000000U, \
        0x00000000U, \
        0xc0400000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x18U, /* FXSR */ { \
        0x06000000U, \
        0x021a2203U, \
        0x26000000U, \
        0x000000c1U, \
        0x00000000U, \
        0x20000000U, \
        0x00000708U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x19U, /* SSE */ { \
        0x04000000U, \
        0x021a2203U, \
        0x24000000U, \
        0x000000c1U, \
        0x00000000U, \
        0x20000000U, \
        0x00000708U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x1aU, /* SSE2 */ { \
        0x00000000U, \
        0x021a2203U, \
        0x24000000U, \
        0x00000041U, \
        0x00000000U, \
        0x20000000U, \
        0x00000708U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x20U, /* SSE3 */ { \
        0x00000000U, \
        0x00180200U, \
        0x00000000U, \
        0x00000040U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x21U, /* PCLMULQDQ */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000400U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x29U, /* SSSE3 */ { \
        0x00000000U, \
        0x00180000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x33U, /* SSE4_1 */ { \
        0x00000000U, \
        0x00100000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x39U, /* AESNI */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000200U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x3aU, /* XSAVE */ { \
        0x00000000U, \
        0x30001000U, \
        0x00000000U, \
        0x00018800U, \
        0x0000000fU, \
        0xdc234020U, \
        0x00005e4aU, \
        0x00000000U, \
        0x00000000U, \
        0x0000000cU, \
        0x00000020U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x3cU, /* AVX */ { \
        0x00000000U, \
        0x20001000U, \
        0x00000000U, \
        0x00010800U, \
        0x00000000U, \
        0xdc230020U, \
        0x00005e42U, \
        0x00000000U, \
        0x00000000U, \
        0x0000000cU, \
        0x00000020U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x54U, /* NX */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00100000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x5dU, /* LM */ { \
        0x00000000U, \
        0x00022000U, \
        0x04000000U, \
        0x00000001U, \
        0x00000000U, \
        0x00000000U, \
        0x00000008U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x5fU, /* 3DNOW */ { \
        0x00000000U, \
        0x00000000U, \
        0x40000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0xa5U, /* AVX2 */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0xdc230000U, \
        0x00005e42U, \
        0x00000000U, \
        0x00000000U, \
        0x0000000cU, \
        0x00000020U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0xb0U, /* AVX512F */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0xdc220000U, \
        0x00005842U, \
        0x00000000U, \
        0x00000000U, \
        0x0000000cU, \
        0x00000020U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0xbeU, /* AVX512BW */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00001042U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000020U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x10cU, /* IBPB */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x40000000U, \
        0x00000000U, \
        0x00000000U, \
        0x18000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x10eU, /* IBRS */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x110f8000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x10fU, /* AMD_STIBP */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00020000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x13aU, /* IBRSB */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x88000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000001U, \
        0x00000000U, \
        0x00000000U, \
        0x00080002U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x13dU, /* ARCH_CAPS */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0xffffffffU, \
        0xffffffffU, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
    { 0x201U, /* EIBRS */ { \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00080000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
        0x00000000U, \
    }, }, \
}

#define INIT_FEATURE_NAMES { \
    { "3dnow", 95U },\
    { "3dnowext", 94U },\
    { "3dnowprefetch", 104U },\
    { "abm", 101U },\
    { "acpi", 22U },\
    { "adx", 179U },\
    { "aesni", 57U },\
    { "amd-ssbd", 280U },\
    { "amd-stibp", 271U },\
    { "apic", 9U },\
    { "arch-caps", 317U },\
    { "avx", 60U },\
    { "avx2", 165U },\
    { "avx512-4fmaps", 291U },\
    { "avx512-4vnniw", 290U },\
    { "avx512-bf16", 325U },\
    { "avx512-bitalg", 204U },\
    { "avx512-ifma", 181U },\
    { "avx512-vbmi", 193U },\
    { "avx512-vbmi2", 198U },\
    { "avx512-vnni", 203U },\
    { "avx512-vpopcntdq", 206U },\
    { "avx512bw", 190U },\
    { "avx512cd", 188U },\
    { "avx512dq", 177U },\
    { "avx512er", 187U },\
    { "avx512f", 176U },\
    { "avx512pf", 186U },\
    { "avx512vl", 191U },\
    { "bhi-ctrl", 420U },\
    { "bhi-no", 532U },\
    { "bmi1", 163U },\
    { "bmi2", 168U },\
    { "btc-no", 285U },\
    { "cet-ibt", 308U },\
    { "cet-ss", 199U },\
    { "cldemote", 217U },\
    { "clflush", 19U },\
    { "clflushopt", 183U },\
    { "clwb", 184U },\
    { "clzero", 256U },\
    { "cmov", 15U },\
    { "cmp-legacy", 97U },\
    { "cr8-legacy", 100U },\
    { "cx16", 45U },\
    { "cx8", 8U },\
    { "dbext", 122U },\
    { "dca", 50U },\
    { "ddp-ctrl", 419U },\
    { "de", 2U },\
    { "doitm", 524U },\
    { "ds", 21U },\
    { "dscpl", 36U },\
    { "dtes64", 34U },\
    { "efro", 234U },\
    { "eibrs", 513U },\
    { "eist", 39U },\
    { "energy-filtering", 523U },\
    { "erms", 169U },\
    { "extapic", 99U },\
    { "f16c", 61U },\
    { "fb-clear", 529U },\
    { "fb-clear-ctrl", 530U },\
    { "fbsdp-no", 526U },\
    { "fdp-excp-only", 166U },\
    { "ffxsr", 89U },\
    { "fma", 44U },\
    { "fma4", 112U },\
    { "fpu", 0U },\
    { "fsgsbase", 160U },\
    { "fxsr", 24U },\
    { "gds-ctrl", 537U },\
    { "gds-no", 538U },\
    { "gfni", 200U },\
    { "hle", 164U },\
    { "htt", 28U },\
    { "hypervisor", 63U },\
    { "ibpb", 268U },\
    { "ibpb-brtype", 380U },\
    { "ibpb-ret", 286U },\
    { "ibrs", 270U },\
    { "ibrs-always", 272U },\
    { "ibrs-fast", 274U },\
    { "ibrs-same-mode", 275U },\
    { "ibrsb", 314U },\
    { "ibs", 106U },\
    { "if-pschange-mc-no", 518U },\
    { "intel-psfd", 416U },\
    { "intel-ssb-no", 516U },\
    { "invpcid", 170U },\
    { "ipred-ctrl", 417U },\
    { "itsc", 232U },\
    { "l1d-flush", 316U },\
    { "lahf-lm", 96U },\
    { "lfence-dispatch", 354U },\
    { "lm", 93U },\
    { "lwp", 111U },\
    { "mca", 14U },\
    { "mcdt-no", 421U },\
    { "mce", 7U },\
    { "mcu-ctrl", 521U },\
    { "md-clear", 298U },\
    { "mds-no", 517U },\
    { "misalignsse", 103U },\
    { "misc-pkg-ctrl", 522U },\
    { "mmx", 23U },\
    { "mmxext", 86U },\
    { "monitor", 35U },\
    { "monitorx", 125U },\
    { "movbe", 54U },\
    { "mpx", 174U },\
    { "msr", 5U },\
    { "mtrr", 12U },\
    { "no-fpu-sel", 173U },\
    { "nodeid-msr", 115U },\
    { "nx", 84U },\
    { "ospke", 196U },\
    { "osvw", 105U },\
    { "osxsave", 59U },\
    { "ovrclk-status", 535U },\
    { "pae", 6U },\
    { "page1gb", 90U },\
    { "pat", 16U },\
    { "pbe", 31U },\
    { "pbrsb-no", 536U },\
    { "pcid", 49U },\
    { "pclmulqdq", 33U },\
    { "pdcm", 47U },\
    { "pge", 13U },\
    { "pku", 195U },\
    { "popcnt", 55U },\
    { "pqe", 175U },\
    { "pqm", 172U },\
    { "prefetchwt1", 192U },\
    { "psdp-no", 527U },\
    { "pse", 3U },\
    { "pse36", 17U },\
    { "psfd", 284U },\
    { "rdcl-no", 512U },\
    { "rdpid", 214U },\
    { "rdrand", 62U },\
    { "rdseed", 178U },\
    { "rdtscp", 91U },\
    { "rrsba", 531U },\
    { "rrsba-ctrl", 418U },\
    { "rsba", 514U },\
    { "rstr-fp-err-ptrs", 258U },\
    { "rtm", 171U },\
    { "rtm-always-abort", 299U },\
    { "sbdr-ssdp-no", 525U },\
    { "sbpb", 379U },\
    { "sep", 11U },\
    { "sgx", 162U },\
    { "sha", 189U },\
    { "skinit", 108U },\
    { "skip-l1dfl", 515U },\
    { "smap", 180U },\
    { "smep", 167U },\
    { "smx", 38U },\
    { "srbds-ctrl", 297U },\
    { "srso-no", 381U },\
    { "ss", 27U },\
    { "ssb-no", 282U },\
    { "ssbd", 319U },\
    { "sse", 25U },\
    { "sse2", 26U },\
    { "sse3", 32U },\
    { "sse4-1", 51U },\
    { "sse4-2", 52U },\
    { "sse4a", 102U },\
    { "ssse3", 41U },\
    { "stibp", 315U },\
    { "stibp-always", 273U },\
    { "svm", 98U },\
    { "syscall", 75U },\
    { "taa-no", 520U },\
    { "tbm", 117U },\
    { "tm1", 29U },\
    { "tm2", 40U },\
    { "topoext", 118U },\
    { "tsc", 4U },\
    { "tsc-adjust", 161U },\
    { "tsc-deadline", 56U },\
    { "tsx-ctrl", 519U },\
    { "tsx-force-abort", 301U },\
    { "umip", 194U },\
    { "vaes", 201U },\
    { "virt-ssbd", 281U },\
    { "vme", 1U },\
    { "vmx", 37U },\
    { "vpclmulqdq", 202U },\
    { "wbnoinvd", 265U },\
    { "wdt", 109U },\
    { "x2apic", 53U },\
    { "xapic-status", 533U },\
    { "xgetbv1", 130U },\
    { "xop", 107U },\
    { "xsave", 58U },\
    { "xsavec", 129U },\
    { "xsaveopt", 128U },\
    { "xsaves", 131U },\
    { "xtpr", 46U },\
}

#define INIT_BIT_NAMES { \
    { "FPU", 0U },\
    { "VME", 1U },\
    { "DE", 2U },\
    { "PSE", 3U },\
    { "TSC", 4U },\
    { "MSR", 5U },\
    { "PAE", 6U },\
    { "MCE", 7U },\
    { "CX8", 8U },\
    { "APIC", 9U },\
    { "SEP", 11U },\
    { "MTRR", 12U },\
    { "PGE", 13U },\
    { "MCA", 14U },\
    { "CMOV", 15U },\
    { "PAT", 16U },\
    { "PSE36", 17U },\
    { "CLFLUSH", 19U },\
    { "DS", 21U },\
    { "ACPI", 22U },\
    { "MMX", 23U },\
    { "FXSR", 24U },\
    { "SSE", 25U },\
    { "SSE2", 26U },\
    { "SS", 27U },\
    { "HTT", 28U },\
    { "TM1", 29U },\
    { "PBE", 31U },\
    { "SSE3", 32U },\
    { "PCLMULQDQ", 33U },\
    { "DTES64", 34U },\
    { "MONITOR", 35U },\
    { "DSCPL", 36U },\
    { "VMX", 37U },\
    { "SMX", 38U },\
    { "EIST", 39U },\
    { "TM2", 40U },\
    { "SSSE3", 41U },\
    { "FMA", 44U },\
    { "CX16", 45U },\
    { "XTPR", 46U },\
    { "PDCM", 47U },\
    { "PCID", 49U },\
    { "DCA", 50U },\
    { "SSE4_1", 51U },\
    { "SSE4_2", 52U },\
    { "X2APIC", 53U },\
    { "MOVBE", 54U },\
    { "POPCNT", 55U },\
    { "TSC_DEADLINE", 56U },\
    { "AESNI", 57U },\
    { "XSAVE", 58U },\
    { "OSXSAVE", 59U },\
    { "AVX", 60U },\
    { "F16C", 61U },\
    { "RDRAND", 62U },\
    { "HYPERVISOR", 63U },\
    { "SYSCALL", 75U },\
    { "NX", 84U },\
    { "MMXEXT", 86U },\
    { "FFXSR", 89U },\
    { "PAGE1GB", 90U },\
    { "RDTSCP", 91U },\
    { "LM", 93U },\
    { "3DNOWEXT", 94U },\
    { "3DNOW", 95U },\
    { "LAHF_LM", 96U },\
    { "CMP_LEGACY", 97U },\
    { "SVM", 98U },\
    { "EXTAPIC", 99U },\
    { "CR8_LEGACY", 100U },\
    { "ABM", 101U },\
    { "SSE4A", 102U },\
    { "MISALIGNSSE", 103U },\
    { "3DNOWPREFETCH", 104U },\
    { "OSVW", 105U },\
    { "IBS", 106U },\
    { "XOP", 107U },\
    { "SKINIT", 108U },\
    { "WDT", 109U },\
    { "LWP", 111U },\
    { "FMA4", 112U },\
    { "NODEID_MSR", 115U },\
    { "TBM", 117U },\
    { "TOPOEXT", 118U },\
    { "DBEXT", 122U },\
    { "MONITORX", 125U },\
    { "XSAVEOPT", 128U },\
    { "XSAVEC", 129U },\
    { "XGETBV1", 130U },\
    { "XSAVES", 131U },\
    { "FSGSBASE", 160U },\
    { "TSC_ADJUST", 161U },\
    { "SGX", 162U },\
    { "BMI1", 163U },\
    { "HLE", 164U },\
    { "AVX2", 165U },\
    { "FDP_EXCP_ONLY", 166U },\
    { "SMEP", 167U },\
    { "BMI2", 168U },\
    { "ERMS", 169U },\
    { "INVPCID", 170U },\
    { "RTM", 171U },\
    { "PQM", 172U },\
    { "NO_FPU_SEL", 173U },\
    { "MPX", 174U },\
    { "PQE", 175U },\
    { "AVX512F", 176U },\
    { "AVX512DQ", 177U },\
    { "RDSEED", 178U },\
    { "ADX", 179U },\
    { "SMAP", 180U },\
    { "AVX512_IFMA", 181U },\
    { "CLFLUSHOPT", 183U },\
    { "CLWB", 184U },\
    { "AVX512PF", 186U },\
    { "AVX512ER", 187U },\
    { "AVX512CD", 188U },\
    { "SHA", 189U },\
    { "AVX512BW", 190U },\
    { "AVX512VL", 191U },\
    { "PREFETCHWT1", 192U },\
    { "AVX512_VBMI", 193U },\
    { "UMIP", 194U },\
    { "PKU", 195U },\
    { "OSPKE", 196U },\
    { "AVX512_VBMI2", 198U },\
    { "CET_SS", 199U },\
    { "GFNI", 200U },\
    { "VAES", 201U },\
    { "VPCLMULQDQ", 202U },\
    { "AVX512_VNNI", 203U },\
    { "AVX512_BITALG", 204U },\
    { "AVX512_VPOPCNTDQ", 206U },\
    { "RDPID", 214U },\
    { "CLDEMOTE", 217U },\
    { "ITSC", 232U },\
    { "EFRO", 234U },\
    { "CLZERO", 256U },\
    { "RSTR_FP_ERR_PTRS", 258U },\
    { "WBNOINVD", 265U },\
    { "IBPB", 268U },\
    { "IBRS", 270U },\
    { "AMD_STIBP", 271U },\
    { "IBRS_ALWAYS", 272U },\
    { "STIBP_ALWAYS", 273U },\
    { "IBRS_FAST", 274U },\
    { "IBRS_SAME_MODE", 275U },\
    { "AMD_SSBD", 280U },\
    { "VIRT_SSBD", 281U },\
    { "SSB_NO", 282U },\
    { "PSFD", 284U },\
    { "BTC_NO", 285U },\
    { "IBPB_RET", 286U },\
    { "AVX512_4VNNIW", 290U },\
    { "AVX512_4FMAPS", 291U },\
    { "SRBDS_CTRL", 297U },\
    { "MD_CLEAR", 298U },\
    { "RTM_ALWAYS_ABORT", 299U },\
    { "TSX_FORCE_ABORT", 301U },\
    { "CET_IBT", 308U },\
    { "IBRSB", 314U },\
    { "STIBP", 315U },\
    { "L1D_FLUSH", 316U },\
    { "ARCH_CAPS", 317U },\
    { "SSBD", 319U },\
    { "AVX512_BF16", 325U },\
    { "LFENCE_DISPATCH", 354U },\
    { "SBPB", 379U },\
    { "IBPB_BRTYPE", 380U },\
    { "SRSO_NO", 381U },\
    { "INTEL_PSFD", 416U },\
    { "IPRED_CTRL", 417U },\
    { "RRSBA_CTRL", 418U },\
    { "DDP_CTRL", 419U },\
    { "BHI_CTRL", 420U },\
    { "MCDT_NO", 421U },\
    { "RDCL_NO", 512U },\
    { "EIBRS", 513U },\
    { "RSBA", 514U },\
    { "SKIP_L1DFL", 515U },\
    { "INTEL_SSB_NO", 516U },\
    { "MDS_NO", 517U },\
    { "IF_PSCHANGE_MC_NO", 518U },\
    { "TSX_CTRL", 519U },\
    { "TAA_NO", 520U },\
    { "MCU_CTRL", 521U },\
    { "MISC_PKG_CTRL", 522U },\
    { "ENERGY_FILTERING", 523U },\
    { "DOITM", 524U },\
    { "SBDR_SSDP_NO", 525U },\
    { "FBSDP_NO", 526U },\
    { "PSDP_NO", 527U },\
    { "FB_CLEAR", 529U },\
    { "FB_CLEAR_CTRL", 530U },\
    { "RRSBA", 531U },\
    { "BHI_NO", 532U },\
    { "XAPIC_STATUS", 533U },\
    { "OVRCLK_STATUS", 535U },\
    { "PBRSB_NO", 536U },\
    { "GDS_CTRL", 537U },\
    { "GDS_NO", 538U },\
}

#define CPUID_BITFIELD_0 \
    bool fpu:1, vme:1, de:1, pse:1, tsc:1, msr:1, pae:1, mce:1, cx8:1, :1, :1, sep:1, mtrr:1, pge:1, mca:1, cmov:1, pat:1, pse36:1, :1, clflush:1, :1, ds:1, acpi:1, mmx:1, fxsr:1, sse:1, sse2:1, ss:1, htt:1, tm1:1, :1, pbe:1

#define CPUID_BITFIELD_1 \
    bool sse3:1, pclmulqdq:1, dtes64:1, monitor:1, dscpl:1, vmx:1, smx:1, eist:1, tm2:1, ssse3:1, :1, :1, fma:1, cx16:1, xtpr:1, pdcm:1, :1, pcid:1, dca:1, sse4_1:1, sse4_2:1, x2apic:1, movbe:1, popcnt:1, tsc_deadline:1, aesni:1, xsave:1, :1, avx:1, f16c:1, rdrand:1, hypervisor:1

#define CPUID_BITFIELD_2 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, syscall:1, :1, :1, :1, :1, :1, :1, :1, :1, nx:1, :1, mmxext:1, :1, :1, ffxsr:1, page1gb:1, rdtscp:1, :1, lm:1, _3dnowext:1, _3dnow:1

#define CPUID_BITFIELD_3 \
    bool lahf_lm:1, cmp_legacy:1, svm:1, extapic:1, cr8_legacy:1, abm:1, sse4a:1, misalignsse:1, _3dnowprefetch:1, osvw:1, ibs:1, xop:1, skinit:1, wdt:1, :1, lwp:1, fma4:1, :1, :1, nodeid_msr:1, :1, tbm:1, topoext:1, :1, :1, :1, dbext:1, :1, :1, monitorx:1, :1, :1

#define CPUID_BITFIELD_4 \
    bool xsaveopt:1, xsavec:1, xgetbv1:1, xsaves:1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_5 \
    bool fsgsbase:1, tsc_adjust:1, sgx:1, bmi1:1, hle:1, avx2:1, fdp_excp_only:1, smep:1, bmi2:1, erms:1, invpcid:1, rtm:1, pqm:1, no_fpu_sel:1, mpx:1, pqe:1, avx512f:1, avx512dq:1, rdseed:1, adx:1, smap:1, avx512_ifma:1, :1, clflushopt:1, clwb:1, :1, avx512pf:1, avx512er:1, avx512cd:1, sha:1, avx512bw:1, avx512vl:1

#define CPUID_BITFIELD_6 \
    bool prefetchwt1:1, avx512_vbmi:1, umip:1, pku:1, :1, :1, avx512_vbmi2:1, cet_ss:1, gfni:1, vaes:1, vpclmulqdq:1, avx512_vnni:1, avx512_bitalg:1, :1, avx512_vpopcntdq:1, :1, :1, :1, :1, :1, :1, :1, rdpid:1, :1, :1, cldemote:1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_7 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, itsc:1, :1, efro:1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_8 \
    bool clzero:1, :1, rstr_fp_err_ptrs:1, :1, :1, :1, :1, :1, :1, wbnoinvd:1, :1, :1, ibpb:1, :1, ibrs:1, amd_stibp:1, ibrs_always:1, stibp_always:1, ibrs_fast:1, ibrs_same_mode:1, :1, :1, :1, :1, amd_ssbd:1, virt_ssbd:1, ssb_no:1, :1, psfd:1, btc_no:1, ibpb_ret:1, :1

#define CPUID_BITFIELD_9 \
    bool :1, :1, avx512_4vnniw:1, avx512_4fmaps:1, :1, :1, :1, :1, :1, srbds_ctrl:1, md_clear:1, rtm_always_abort:1, :1, tsx_force_abort:1, :1, :1, :1, :1, :1, :1, cet_ibt:1, :1, :1, :1, :1, :1, ibrsb:1, stibp:1, l1d_flush:1, arch_caps:1, :1, ssbd:1

#define CPUID_BITFIELD_10 \
    bool :1, :1, :1, :1, :1, avx512_bf16:1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_11 \
    bool :1, :1, lfence_dispatch:1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, sbpb:1, ibpb_brtype:1, srso_no:1, :1, :1

#define CPUID_BITFIELD_12 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_13 \
    bool intel_psfd:1, ipred_ctrl:1, rrsba_ctrl:1, ddp_ctrl:1, bhi_ctrl:1, mcdt_no:1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_14 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_15 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_16 \
    bool rdcl_no:1, eibrs:1, rsba:1, skip_l1dfl:1, intel_ssb_no:1, mds_no:1, if_pschange_mc_no:1, tsx_ctrl:1, taa_no:1, mcu_ctrl:1, misc_pkg_ctrl:1, energy_filtering:1, doitm:1, sbdr_ssdp_no:1, fbsdp_no:1, psdp_no:1, :1, fb_clear:1, fb_clear_ctrl:1, rrsba:1, bhi_no:1, xapic_status:1, :1, ovrclk_status:1, pbrsb_no:1, gds_ctrl:1, gds_no:1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_17 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_18 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_19 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_20 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_21 \
    bool :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1, :1

#define CPUID_BITFIELD_22 \
    uint32_t :32 /* placeholder */

#define CPUID_BITFIELD_23 \
    uint32_t :32 /* placeholder */

#define CPUID_BITFIELD_24 \
    uint32_t :32 /* placeholder */

#define CPUID_BITFIELD_25 \
    uint32_t :32 /* placeholder */


#endif /* __XEN_X86__FEATURESET_DATA__ */
